config/routes.rb
FindYourCar::Application.routes.draw do
  
  root :to => "home#index"
  
  # get "mission/index"

  resources :mission, :only => [:index]

  resources :surveys, :only => [:new, :create, :show, :destory]

  resources :cars, :only => [:index, :show]

  resources :users, :only => [:new, :create, :show, :destroy]

  resources :sessions, :only => [:new, :create, :destroy]

  # get '/cars/:name', :to => "cars#show", :as => 'car'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	get_images
  end

  def get_images
	  @image_array = []
  	@cars = Car.all
  	@cars.each do |car|
  		@image_array << car.name
  	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form.html.erb
<%= form_for @survey do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this reservation from being saved:</h2>
      <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="inline">
    <div class="field">
      <%= f.label :price_range %><br />
      <%= f.select :price_range, @PRICE_RANGES %>
    </div>
  </div>
  <div class="inline">
    <div class="field">
      <%= f.label :type %><br />
      <%= f.select :type, @TYPES %>
    </div>
  </div>
  <div class="inline">
    <div class="field">
      <%= f.label :transmission %><br />
      <%= f.select :transmission, @TRANS %>
    </div>
  </div>
  <div class="inline">
    <div class="field">
      <%= f.label :safety %><br />
      <%= f.select :safety, @SAFETY %>
    </div>
  <div class="inline">
    <div class="field">
      <%= f.label :fuel_type %><br />
      <%= f.select :fuel_type, @FUEL_TYPES %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/_images.html.erb
<% @image_array.each do |car| %>
	<li>
    <img src="/assets/cars/<%= @image_array.sample %>.jpg" /> 
    <p class="flex-caption"></p>
  </li>
<% end %>

app/views/home/index.html.erb
<div class="hero">
	<div class="span6 offset1 hero-text">
		<h1 style="font-size:46px;padding-top:30px;">
			Find your perfect car

		</h1>
		<p>
			Finding your perfect car is <br>
			only a few clicks away
		</p>
		<a href="<%= new_survey_path %>" class="myButton">
			Fill Out Survey
		</a>
	</div>
	<div class="span4">
		<div class="flexslider">
		  <ul class="slides">
		  	<%= render 'images' %>
		  </ul>
		</div>
	</div>
</div>

<div class="how-it-works">
	<div class="row">
		<h1 class="title" style="font-size:50px;"><a name="how"></a>HOW IT WORKS</h1>
	</div>

	<div class="row">
		<div class="column"> 
				
				<h3>Fill Out Survey</h3>
				<p>
					Only complete the fields <br> 
					that are important to you
				</p>
				<a href="/surveys/new"><img src="/assets/Image1.png"></a>
		</div>

		<div class="column">
			
			<h3>View the Results</h3>
			<p>
				Compare the cars that matched <br> 
				your survey 
			</p>
			<img src="/assets/Image2.png">
		</div>

		<div class="column">
			
			<h3>Go Shopping</h3>
			<p>
				Knowing that you are making <br> 
				a more informed descision
			</p>
			<a href="/cars"><img src="/assets/Image3.png"></a>
		</div>
	</div>
</div>


<div class ="mission">
	<div class="row">
		<h1><a name="mission"></a>OUR MISSION</h1>
	</div>
	<div class="row">
		<p>
			Most new cars buyers are not sure how to choose a car that best suits their needs. We at bestcarforyou.com have built an easy-to-use tool that helps car buyers select the best car for them bassed on their preference of features and attributes.
		</p>
		<p></p>
		<p>
			Our recommendations are designed to be completely unbiased and are based solely on facts and figures that are published by car manufacturers and Consumer Reports. We do not solicit any car manufacturer advertising and we do not sell cars. We simply provide the facts based on individual requirements and let the buyer decide which vehicle to pruchase.
		</p>
	</div>
</div>









		