config/routes.rb
FindYourCar::Application.routes.draw do
  
  root :to => "home#index"
  
  # get "mission/index"

  resources :mission, :only => [:index]

  resources :surveys, :only => [:new, :create, :show, :destory]

  resources :cars, :only => [:index, :show]

  resources :users, :only => [:new, :create, :show, :destroy]

  resources :sessions, :only => [:new, :create, :destroy]

  # get '/cars/:name', :to => "cars#show", :as => 'car'

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="social">
		<ul class="footer_links">
				<li><small>Connect:</small></li>
				<li>
					<a href="#" class="facebook">Facebook</a>
				</li>
				<li>
					<a href="#" class="twitter">Twitter</a>
				</li>	
		<!-- 		<li>
					<a href="#" class="Pinterest">Pinterest</a>
				</li> -->
				<li style="float:right;margin-right:20px;"><small>©Andrew Khajerian, FindYourCar 2013</small></li>		
			</ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="span2">
    <h1 class="logo">
      <a href="/"><img src="/assets/Logo.png"></a>
    </h1>
  </div>

  <div class="main-nav">
    <nav>
    	<ul class="nav">
        <li><a href="/#how">How it Works</a></li>
      	<li><%= link_to "Cars", cars_path %></li>
        <li><a href="/#mission">Mission</a></li>
  		</ul>
    </nav>
  </div>

  <div class="right-nav">
    <ul>
      <% if current_user %>
        <li class="pull-right login"><%= link_to "Logout", session_path %></li>
      <% else %>
        <li class="pull-right">
          <button class='btn'><%= link_to "Sign Up", new_user_path %></button>
        </li>
        <li class="pull-right login"><%= link_to "Log In", new_session_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindYourCar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<div class="main">	
			<%= render 'layouts/header' %>
			
			<% if flash[:notice] %>
		    <div class="alert alert-success">
		      <%= flash[:notice] %>
		    </div>
		  <% elsif flash[:alert] %>
		    <div class="alert alert-error">
		      <%= flash[:alert] %>
		    </div>
		  <% end %>

  		

			<%= yield %>

			<%= render 'layouts/footer' %>
		</div>



	</body>
</html>